spring.application.name=dispatch-core-api

# Configuração do banco de dados (Postgres local via Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/dispatch-core
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Flyway
spring.flyway.enabled=true
spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}